name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

env:
  TAG: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: 'microsoft'
          java-version: 25

      - name: Build with Gradle
        run: ./gradlew build

      - name: Maven Release
        if: ${{ secrets.MAVEN_UPLOAD_URL }}
        env:
          MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
        run: ./gradlew publish

      - name: Publish (GitHub Releases)
        id: publish_github
        uses: Kira-NT/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659 # (new) v3.3.0
        with:
          github-token: ${{ github.token }}
          version: ${{ env.TAG }}
          files: |
            ./**/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            ./**/build/libs/*-@(sources|javadoc).jar
