name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

env:
  TAG: ${{ github.ref_name }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21
      - name: Copy Maven Upload URL
        id: extract_maven_upload_url
        run: echo "maven_upload_url=${{ secrets.MAVEN_UPLOAD_URL }}" >> $GITHUB_OUTPUT
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assemble --rerun-tasks
      - name: Maven Release
        if: steps.extract_maven_upload_url.outputs.maven_upload_url
        env:
          MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
        run: ./gradlew publish
      - name: Publish (GitHub Releases)
        id: publish_github
        uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659 # (new) v3.3.0
        with:
          github-token: ${{ github.token }}
          version: ${{ env.TAG }}
          files: |
            build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            build/libs/*-@(sources|javadoc).jar
